# Generated by Django 5.2.7 on 2026-01-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('IE', 'Ireland')], max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('estimated_living_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('admission_requirements', models.TextField(blank=True)),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('graduation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_ug_tuition', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('avg_pg_tuition', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('financial_aid', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='universities/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=3)),
                ('overview', models.TextField(blank=True)),
                ('modules', models.TextField(blank=True)),
                ('entry_requirements', models.TextField(blank=True)),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('start_month', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('ucas_cao_code', models.CharField(blank=True, max_length=20)),
                ('work_placement', models.BooleanField(default=False)),
                ('intake_months', models.CharField(max_length=100)),
                ('course_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.university')),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residency', models.CharField(choices=[('HOME', 'Home'), ('EU', 'EU'), ('INTL', 'International')], max_length=5)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('eligibility', models.TextField()),
                ('award_type', models.CharField(max_length=100)),
                ('award_value', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='app.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('CUG', 'Complete University Guide'), ('QS', 'Top Universities (QS)')], max_length=10)),
                ('year', models.IntegerField()),
                ('arts_humanities', models.IntegerField(blank=True, null=True)),
                ('life_sciences', models.IntegerField(blank=True, null=True)),
                ('engineering_technology', models.IntegerField(blank=True, null=True)),
                ('natural_sciences', models.IntegerField(blank=True, null=True)),
                ('social_sciences_management', models.IntegerField(blank=True, null=True)),
                ('staff_student_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('international_students_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('graduate_prospects', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('student_satisfaction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='app.university')),
            ],
        ),
    ]
