# Generated by Django 5.2.7 on 2026-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PGT', 'Postgraduate')], max_length=3),
        ),
    ]
