# Generated by Django 5.2.7 on 2026-01-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='banner',
            field=models.ImageField(blank=True, upload_to='universities/banners/'),
        ),
    ]
