# Generated by Django 5.2.7 on 2026-01-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_university_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='banner',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
