# Generated by Django 5.2.7 on 2026-01-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_university_banner_alter_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityranking',
            name='overall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
