# Generated by Django 5.2.7 on 2026-01-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_universityranking_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityranking',
            name='world_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
