# Generated by Django 5.2.7 on 2026-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blogpost_excerpt_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (160 characters max)', max_length=160),
        ),
    ]
