# Generated by Django 5.2.7 on 2026-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blogpost_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (recommended 150-160 characters)'),
        ),
    ]
