# Generated by Django 5.2.7 on 2026-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blogcategory_blogpost_category_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PGT', 'Postgraduate'), ('TOPUP', 'Top-up'), ('MRES', 'MRes')], max_length=10),
        ),
    ]
