# Generated by Django 5.2.7 on 2026-04-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_scholarship_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)'), ('KES', 'Kenyan Shilling (KSh)'), ('ZAR', 'South African Rand (R)'), ('INR', 'Indian Rupee (₹)'), ('CNY', 'Chinese Yuan (¥)'), ('PKR', 'Pakistani Rupee (Rs)'), ('BDT', 'Bangladeshi Taka (৳)')], max_length=3, unique=True)),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('rate_to_gbp', models.DecimalField(decimal_places=4, help_text='Exchange rate relative to 1 GBP (e.g., if 1 GBP = 1.27 USD, enter 1.27)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['currency_code'],
            },
        ),
    ]
